name: JEPX Fetch Data

on:
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch Latest Data
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 6
          retry_wait_seconds: 600
          command: python fetch_data.py

      - name: Commit and Push
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add data/*.csv
          git diff --staged --quiet || git commit -m "Update JEPX data $(date +'%Y-%m-%d')"
          git push

  trigger-report:
    needs: fetch-data
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Send Report
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/naokazut/jepx-monitor/actions/workflows/workflow-mail.yml/dispatches \
            -d '{"ref":"main"}'
